apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: qe-broker-root-config
  title: QE Broker Root Configuration
  namespace: quality-community
  description: A root collection of all QE Broker configurations for Backstage.
spec:
  owner: group:redhat/quality-community
  targets:
    - ./catalog/system/broker.yaml

